### ISSUE TITLE
对于网站提个建议

### ISSUE THREAD

**Issue by sumingyd** [sparkssssssssss/epg#1]
似乎网站的CF超量了，网站上的反馈界面一直522超时。
在这里提个建议吧
建议自主添加频道的时候，如果频道已存在的情况下，弹窗内容改为：频道已存在，当前频道映射名为xxx

**Comment by sparkssssssssss** [comment]
不是cf超量了,是垃圾vps在维护,失联了....
自主添加节目已做了存在提示.

**Comment by sumingyd** [comment]
> 不是cf超量了,是垃圾vps在维护,失联了.... 自主添加节目已做了存在提示.

这里的更新慢了，都是昨天的文件了。。。要不然你把讨论区打开。。想说个啥得用问题这个标签。。。

**Comment by sumingyd** [comment]
刚才看了下，我主要是想表达的提示出来：当前频道名
